apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-workload-sa
  namespace: sample
  annotations:
    azure.workload.identity/client-id: "${WORKLOAD_CLIENT_ID}"
  labels:
    azure.workload.identity/use: "true"

